name: analysis_lints
version: 1.0.8
homepage: https://github.com/SunnatilloShavkatov/analysis_lints.git
description: "Unified analysis rules set for Flutter and Dart projects"

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  lints: ^6.1.0
  flutter_lints: ^6.0.0
